### ISSUE TITLE
$HOME/.tab/completion is not created

### ISSUE THREAD

**Issue by steven807** [austinjones/tab-rs#151]
When initially running `tab --install bash` I get:

    Error: No such file or directory (os error 2)

I had to `mkdir ~/.tab/completion` for it to work.

**Comment by austinjones** [comment]
Thanks for the bug report!  I'll fix it ASAP.

**Comment by austinjones** [comment]
Resolved in [v0.3.7](https://github.com/austinjones/tab-rs/releases/tag/v0.3.7).
