### ISSUE TITLE
Use XDG Base Directory Specification

### ISSUE THREAD

**Issue by savq** [austinjones/tab-rs#159]
The project is already using the [dirs](https://docs.rs/dirs/3.0.1/dirs/) crate which provides information on the XDG directory specification. I think it would be better if the project used the `config_dir` and `data_dir` functions, instead of creating a directory directly in $HOME.

**Comment by austinjones** [comment]
Ah, good suggestion!  I'll look into this.

**Comment by savq** [comment]
That'd be great thank you, and thank you for writing tab! It's the only term-multiplexer that has worked "out-of-the-box" for me.

**Comment by austinjones** [comment]
@savq I'm glad you like it!  

And it's really great to hear it worked out of the box.  My top design goal was to be intuitive, and it sounds like it's working.

**Comment by austinjones** [comment]
I've implemented this in #171 and it will be released in 0.4.0.

**Comment by austinjones** [comment]
In case anyone needs to find the tab runtime directory, here are the paths used in 0.4.0:
- Linux: `$XDG_DATA_HOME/tab` or `$HOME/.local/share/tab`
- MacOS: `$HOME/Library/Application Support/tab`

**Comment by austinjones** [comment]
Closing, this was released in [v0.4.0](https://github.com/austinjones/tab-rs/releases/tag/v0.4.0)!
