### ISSUE TITLE
tab: unsupported terminal app: alacritty

### ISSUE THREAD

**Issue by rsignavong** [austinjones/tab-rs#161]
Hello,

After installed tab from brew, I tried the command `tab --install all` and then an macOS popping shown up asking for permissions but I don't remember what was it and accepted it.

Then the following error message is displayed whenever I launch a tab command.
```
~ on ☁️  (us-east-1)
❯ tab
tab: unsupported terminal app: alacritty

~ on ☁️  (us-east-1)
❯ tab --install all
tab: unsupported terminal app: alacritty

~ on ☁️  (us-east-1)
❯ tab --help
tab: unsupported terminal app: alacritty
```

What should I do?

**Comment by austinjones** [comment]
Hi @rsignavong,
This is caused by a conflict with the `osx` oh-my-zsh plugin.  You should be able to fix it by removing that from your `~/.zshrc`.

**Comment by austinjones** [comment]
If you want more details I wrote a bit more about it in #156

**Comment by rsignavong** [comment]
Okay, I have removed this plugin that I have never used... and now it works!

By the way, you should update the doc for starship configuration because `prompt_order` is now called `format`.

**Comment by austinjones** [comment]
Ah good catch!  0.45 came out!

Glad it's working!  Feel free to reach out if you run into any other issues or have ideas for features.
