### ISSUE TITLE
"tab -w inexistent" should warn or error

### ISSUE THREAD

**Issue by userxfce** [austinjones/tab-rs#164]
current behaviour, when attempting to close unexistent tab: silent
desired behaviour: display a warning or an error

**Comment by austinjones** [comment]
Yeah, this makes sense!  I'll add this to v0.4.0

**Comment by userxfce** [comment]
Has this been fixed in commit a0d726e588122cbcb6e61be61ffa83f84ee2f31d?
It now displays "Tab not running: inex/".

**Comment by austinjones** [comment]
Yes, in #176.  I'm preparing to release it in 0.4.0 today.

**Comment by austinjones** [comment]
Closing, [v0.4.0](https://github.com/austinjones/tab-rs/releases/tag/v0.4.0) is released!
