### ISSUE TITLE
Document how to disconnect from long-running processes in README.md (using ctrl-W)

### ISSUE THREAD

**Issue by sabitm** [austinjones/tab-rs#172]
Hi, sorry if this is a silly question. But, how do i change to different tab when some command running?
Let's say if i run `sleep 1m` on tab 1/ and then i want to change to tab 2/, is there any method that i can do?

I've tried to bind `tab 1` and `tab 2` to a key in zsh using bindkey, but it doesn't work. Instead, it print the corresponding character to terminal (like `^[1`, `^[2`). I'm using alacritty as my terminal and try to bind that command in the configuration file.

`   - { key: Key2, mods: Alt, command:
       { program: "tab", args: ["2"] } }
`

But, based on the alacritty config docs, that keybinding will fork and execute the command inside when executed. So it doesn't work too.
The trick i've found and works is by using semicolon for separating command like this, `tab 2; sleep 1m`. so it will change to tab 2 first, and then execute sleep. But, whenever i come back to tab 1, i can't move to tab 2 anymore without pushing it to background.

I'm curious if there are any other methods that i can try.
Thanks

**Comment by austinjones** [comment]
Good question!  I think I need to improve the readme docs to make this 'interactive program' case more clear.

You can use `ctrl-W` to disconnect the session.  Tab will drop you back to your root shell, and from there you can use the `tab <NAME>` command to select a new tab.  This should work with interactive programs (vi/nano/top), and with local servers that are producing logs.

I use alacritty as well - I'll take a look at the shortcut and figure out why it doesn't work.  My first guess is that it doesn't inherit the environment variables of the shell.  Tab uses inherited env variables to retask your outer `tab` client, so you don't end up with nested sessions.

**Comment by sabitm** [comment]
Wow, silly me. I should've tried that command XD. Thanks very much
if you're curious, this is the output of `ps aux` when `tab 1` command executed through alacritty's keybinding:

```
sabit      77461  0.2  0.1 554420  6036 pts/3    Sl+  00:53   0:00 tab
sabit      77466  0.1  0.1 283340  6328 pts/3    Sl+  00:53   0:00 /usr/bin/tab --_launch daemon --log info
sabit      77471  0.0  0.0 283964  4296 pts/3    Sl+  00:53   0:00 /usr/bin/tab --_launch pty --log info
sabit      78643  0.7  0.1 284028  6380 ?        Ssl  00:55   0:00 tab 1
sabit      78653  0.1  0.0 283964  5412 pts/3    Sl+  00:55   0:00 /usr/bin/tab --_launch pty --log info
sabit      78735  0.1  0.1 284028  6184 ?        Ssl  00:55   0:00 tab 1
sabit      78809  0.5  0.1 284032  6196 ?        Ssl  00:55   0:00 tab 1
sabit      78829  0.6  0.1 284016  6472 ?        Ssl  00:55   0:00 tab 1
sabit      78862  1.0  0.1 284020  6452 ?        Ssl  00:56   0:00 tab 1
sabit      78879  0.0  0.1 284032  6128 ?        Ssl  00:56   0:00 tab 1
sabit      78899  0.0  0.0   9688  4264 pts/0    S+   00:56   0:00 rg tab
```

The `?` on `TTY` column seems suspicious. Maybe that's the problem?

**Comment by austinjones** [comment]
Thanks for the output!  In the retask case the tab command exits, so it looks like these commands are spawning as an interactive client.

**Comment by sabitm** [comment]
Yeah, that's true. Maybe that's just how alacritty's `command:` keybinding works right? And that's no longer an issue for me too with `Ctrl + w` now works and i can use other keybinding like zsh' bindkey.

**Comment by austinjones** [comment]
Excellent!  I'll leave this open until I improve the docs - I'm planning on adding a section on common navigation - as I've been working on some features that help with multiple workspaces.

**Comment by sabitm** [comment]
Great! Thanks for your good work. Tab-rs has been a nice fit for me!

**Comment by austinjones** [comment]
No problem!  I'm glad it's working out for you.

**Comment by austinjones** [comment]
Closing, [v0.4.0](https://github.com/austinjones/tab-rs/releases/tag/v0.4.0) is released!  And documentation is on `main`.
