### ISSUE TITLE
Add binaries compiled fro ARM platform (raspberry pi)

### ISSUE THREAD

**Issue by shytikov** [austinjones/tab-rs#231]
I found `tab-rs` much more usable comparing to `screen` and `tmux`, but unfortunately cannot use it on my raspberry pi 3a+. 

I'm just not able to install `rust`. I assume `rustup` just fails to unpack `rustc` archive, because of 512 MB RAM. Don't quote me on that but it looks like it uses RAM as temporary storage and then it exhausted it just dies.

But that basically means I cannot use `tab-rs` there, because I cannot compile. It would be nice if ARMv6 / ARMv7 binaries would be supplied as part of release. 

Please and thank you :)

**Comment by austinjones** [comment]
I'll take a look at this.  

In the meantime, you might be able to cross-compile it using a gcc-arm linker from another machine.  https://chacin.dev/blog/cross-compiling-rust-for-the-raspberry-pi/

**Comment by austinjones** [comment]
I got this working!  I'm rebuilding v0.5.1 for ARMv7.

**Comment by austinjones** [comment]
@shytikov, I just uploaded an ARMv7 binary to the [v0.5.1](https://github.com/austinjones/tab-rs/releases/tag/v0.5.1) release page.

**Comment by austinjones** [comment]
I just pushed v0.5.2 with an ARM build.  Closing this.
