### ISSUE TITLE
Switching tabs leaves garbage in shell prompt

### ISSUE THREAD

**Issue by casonadams** [austinjones/tab-rs#238]
tab version: 0.5.1

`vi` in one tab (pair)
Created another tab (new) from (inside of pair tab)
Switch between tabs via `ctrl-T`

![tab_garbage_switch](https://user-images.githubusercontent.com/17597548/99930768-825fae00-2d0f-11eb-93db-05b4c6ede5ab.gif)

**Comment by austinjones** [comment]
I haven't seen this one before.  Which shell are you using?

**Comment by casonadams** [comment]
This is a bash shell. (OSX)

**Comment by austinjones** [comment]
Ah, yes!  This one is really interesting.  I was able to reproduce it.  
- `tab any`
- `vi foo`
- `q!`
- `ctrl-T other`
- `ctrl-T any`

It happens when vi was opened within a session and then quit.  It affects the session, but not the client.  It looks like these characters are even saved in the scrollback buffer. 

Most of the bugs like this that I've seen relate to the session leaking state to the root terminal.  But something very different is going on here.

**Comment by austinjones** [comment]
This is an ANSI escape code called 'Device Status Report'.  The full string is `[2;2R[3;1R]10;rgb:c6c6/c6c6/c4c4`.

https://en.wikipedia.org/wiki/ANSI_escape_code

```
Reports the cursor position (CPR) to the application as (as though typed at the keyboard) ESC[n;mR, where n is the row and m is the column.) 
```

The escape sequence `CSI 6n` is being saved in the scrollback buffer, which is causing the terminal to echo the cursor position.  But the shell is the active application, not `vi`...

**Comment by austinjones** [comment]
Here is another one from the OSX terminal & fish:
`[2;2R[3;3R[>1;95;0c]10;rgb:ffff/ffff/ffff`

**Comment by austinjones** [comment]
Yep!  Fixed it by filtering that escape sequence in the scrollback buffer.

**Comment by mrksu** [comment]
Hi, this might be a separate issue but I'm also getting some control sequences in my terminal after switching between tabs:

* `]11;rgb:1d1d/1f1f/2121` in Fish
* `11;rgb:1d1d/1f1f/2121` in Bash

In both cases, I'm using the Starship prompt in my Fish or Bash, and in both cases, I opened and closed Neovim in the tab.

My `tab` version is 0.5.1.

Should I open a separate issue or give you more details?

**Comment by austinjones** [comment]
Hi @mrksu,
Yeah, it's a related issue.  It's another ANSI escape sequence that is replied to by the terminal emulator.  I diagnosed it and I'm working on a fix for the next patch release.

**Comment by austinjones** [comment]
@casonadams v0.5.2 is out with this fix, and your enhancement of `tab --list`!

**Comment by shytikov** [comment]
I'm still seeing that `v0.5.5` on Mac...
