### ISSUE TITLE
Tab window size fails to adjust on tab switch after a window resize

### ISSUE THREAD

**Issue by casonadams** [austinjones/tab-rs#239]
tab version: 0.5.1

Open terminal in 80x80
Create tab
Create second tab
Open file with `vi`
Resize window to 80x160
Switch tab to second tab via `ctrl+T`
Switch tab back to first tab `vi` `ctrl+T`
Window is original 80x80

![tab_terminal_resize](https://user-images.githubusercontent.com/17597548/99931393-92788d00-2d11-11eb-968a-9d2f8398cdd7.gif)

**Comment by austinjones** [comment]
This was fixed in #230.

**Comment by casonadams** [comment]
Should we close this one out then?

**Comment by austinjones** [comment]
Yeah.  I think I'll be ready to release the fix tonight, or maybe tomorrow.

Thanks so much for all these reports!  They really help w/ nailing down the outstanding bugs.

**Comment by casonadams** [comment]
This is awesome that you are jamming on these issues so quickly!  I really want to switch from `tmux` to `tab`!  I love to remote pair program and having a tab session available to pair in is fantastic! The sandboxing is super cool BTW!

**Comment by austinjones** [comment]
Yeah!  Really cool to hear that!  `tmux` is definitely more stable, but `tab` is getting there.

It's a small-ish project with low tech debt and a ton of testing, so it's easy to move fast.  It takes maybe 6-8 hours a week to keep things moving.  And rust+async are killer... the performance is awesome...
