### ISSUE TITLE
Failed to initialize the tab command: IO error: Connection refused

### ISSUE THREAD

**Issue by sabitm** [austinjones/tab-rs#244]
Hi again!

This time, i encounter some random errors within some login session. This is truly random though, and sometimes i just have to restart my computer to get it working again. But, it bugs me enough when one restart can't solve this problem. Sometimes i need to restart twice. This is the exact error:

```
$ tab home
05:20:29.833 CMD [ERROR] Failed to initialize the tab command: IO error: Connection refused (os error 111)
Error: IO error: Connection refused (os error 111)
```
Funnily, i can run `tab` command with sudo to get rid of the error. But, yeah... you can only use it in su environment.

```
$ sudo tab home
# (in su env)
```

This seems like a permission problem. But i think it's funny because.normally, i can get it to work without being root. I'm curious and how can i debug further?

**Comment by austinjones** [comment]
Hi @sabitm,
Tab launches the daemon as the current user when you first run the `tab` command.  The command client needs access to the [dirs::data_dir()[(https://docs.rs/dirs/3.0.1/dirs/fn.data_dir.html) path.

There are a few things you could check when this happens:
- The data_dir has a daemon-pidfile.yml.  is that process running, and is it the command `tab --_launch daemon`?
- You can also launch the daemon in debugging mode by running `tab --shutdown` and `tab --log debug`, which will launch the daemon with debug logs enabled.  It inherits the client log level when it is launched.
- Usually, you can shutdown the daemon using `tab --shutdown`, but `pkill tab` works too.  If it works after that, then it's definitely an issue with the daemon that was killed.

I'll take a look at this and see if I can reproduce it, or spot an obvious issue in the code.

**Comment by austinjones** [comment]
Hmm, I got a similar error by launching the daemon with `sudo tab foo`, then trying to connect as my normal user:
```
16:04:44.862 CMD [ERROR] Failed to initialize the tab command: Permission denied (os error 13)
Error: Permission denied (os error 13)
```

Is the daemon being launched as root, or another local user?

**Comment by nebbishhacker** [comment]
I've just encountered the exact same error as @sabitm. As far as I could tell, the tab daemon was not running, but the `daemon-pid.yml` was still there.

I deleted `~/.local/share/tab/daemon-pid.yml` and it started working again.

**Comment by sabitm** [comment]
Sorry for the late reply. I have a hard time reproducing this problem again. It's not clear to me what the cause of this. And I'm not encountering this problem again since. Here's my insight last time I got the error.

- When the error happened, there was a `daemon-pid.yml`. But the tab daemon was not running (as said by @nebbishhacker)
- Running all tab command (--shutdown, --log, etc.) results in the above error. And I can't run the daemon because of this

Does `daemon-pid.yml` must be deleted when the daemon process got killed?

> launching the daemon with `sudo tab foo`, then trying to connect as my normal user

How do you launch the daemon and connect it from another user? For me, there will be multiple instances of daemon with different pid and user when i try to launch `tab` multiple times from different user

> I deleted `~/.local/share/tab/daemon-pid.yml` and it started working again.

This is interesting though. I'm not trying to delete this file when I got the error last time. Let's see when the error pops up again. Thanks

**Comment by austinjones** [comment]
@sabitm, no worries.  I understand what is happening here now, and how to fix it.  Thank you so much (and @nebbishhacker) for the info!

If the daemon shuts down gracefully, it deletes it's pidfile.  Tab launches the daemon if the pidfile is missing, and it also does so if no process is running with an existing pidfile.  It looks like the command-line client thinks the daemon is running, but it is not.  And I think it's because the pidfile was created on a previous boot, and conflicts with a running (non-tab) process in the current boot.  Tricky..

I'll push a fix in a few days.

**Comment by sabitm** [comment]
No problem @austinjones !
Thanks for clarifying this. It makes sense to me now. That's definitely the problem I have. Some applications (like chrome) spawn many processes and some of them might conflict with tab client.

**Comment by austinjones** [comment]
I was able to reproduce and fix the issue.  The release is going out this evening.

**Comment by sabitm** [comment]
Thanks very much 🎉
