### ISSUE TITLE
Support CTRL+N/CTRL+P keybindings in fuzzy finder

### ISSUE THREAD

**Issue by jrop** [austinjones/tab-rs#260]
Common keybindings for "next" (CTRL+N) and "previous" (CTRL+P) are helpful alternatives to using the arrow keys.

BTW, I'm loving tab so far!

**Comment by austinjones** [comment]
Sure!  This would be simple to add and would be a nice improvement.

**Comment by casonadams** [comment]
@austinjones I would like to take a stab at this one.  Any guidance you can share would be awesome!
