### ISSUE TITLE
In fuzzy finder, when no query for tab name is entered sort list by most recently used tabs

### ISSUE THREAD

**Issue by DhruvDh** [austinjones/tab-rs#265]
With the current tab being second on the list, and the most recently used tab (last used) being first .

What this would allow for is to press `Ctrl + T` and `Enter` in quick succession to always switch to the last tab. As shown in this video, if it was implementing switching back and forth between two tabs would be a breeze. (Video shows current behaviour, but does demonstrate how quick switching would work)

https://user-images.githubusercontent.com/14926467/102572942-5be92480-40bb-11eb-93a6-bbbab647b969.mp4

**Comment by DhruvDh** [comment]
Alternatively, switch to most recently used tab when `Ctrl + T` is pressed in the Fuzzy finder view. This would allow double tapping `Ctrl + T` to quick switch to last tab.

**Comment by austinjones** [comment]
Damn, this would be cool.  I'm adding it to the next feature release!

**Comment by bbigras** [comment]
It could also be nice to sort by the most frequently selected ones and have the last used one first for fast alternation between 2 tabs.

**Comment by austinjones** [comment]
@bbigras Yeah, I think so too!  I implemented most of what is needed in #298 but I need to swap the two most recently selected tabs so `ctrl-T enter` acts like alt-tab.
