### ISSUE TITLE
starship prompt reverts to PS1 on entering a tab

### ISSUE THREAD

**Issue by TheWithz** [austinjones/tab-rs#267]
As seen in the screen shots, I'm using tab and starship together. terminal is alacritty.
when I'm outside any tabs, starship prompt behaves as normal. However when I enter a tab, my PS1 shows up instead of the starship prompt, and it's duplicated.
`bash: 5.1.0(1)` 
`alacritty: 0.6.0`
`tab: 0.5.2`
`starship: 0.47.0`
`Operating system: Gentoo 5.10.0`
# the issue
![2020-12-18-223853_1890x555_scrot](https://user-images.githubusercontent.com/8269545/102680053-09733b00-4183-11eb-91bf-fb576fb187de.png)
# starship config
![2020-12-18-224001_1376x733_scrot](https://user-images.githubusercontent.com/8269545/102680054-0a0bd180-4183-11eb-9880-9a114653b4bc.png)
# relevant portion of alacritty config
![2020-12-18-224445_982x337_scrot](https://user-images.githubusercontent.com/8269545/102680055-0a0bd180-4183-11eb-9d0a-360f83b267bb.png)

**Comment by austinjones** [comment]
Hi @TheWithz,
Ah, I think that I'm not setting `--login` when launching bash, so your config in `~/.bash_profile` / `~/.bash_login` / `~/.profile` isn't being picked up.  It's a simple fix - I'll include this in 0.5.3 (I'm hoping to push it this weekend).

In the meantime you could move the starship config to `~/.bashrc`, which I think will fix it.

**Comment by austinjones** [comment]
@TheWithz I just pushed a fix in [v0.5.3](https://github.com/austinjones/tab-rs/releases/tag/v0.5.3).

**Comment by TheWithz** [comment]
@austinjones It works great. Thanks for your hard work!
