### ISSUE TITLE
Rendering issue with kakoune

### ISSUE THREAD

**Issue by RemiIia** [austinjones/tab-rs#268]
Inside Tab Kakoune works strangely.
**Versions**:
* Tab 0.5.2
* Alacritty 0.6.0
* NixOS 21.03 (Okapi)
* Kakoune 2020.09.01

![Peek 2020-12-19 14-16](https://user-images.githubusercontent.com/33205215/102688071-53046a00-4205-11eb-8202-031cea304bda.gif)

**Comment by austinjones** [comment]
Interesting.  I use Fish/Alacritty/Starship as well, and I have the same Kakoune version as you.  I'm not seeing the same behavior.  I'll try a VM and see if I can reproduce it.

Thanks for the bug report!

**Comment by austinjones** [comment]
Hmm, I still can't reproduce it.  Could you send me your kakrc?

It's definitely related to terminal size.  There are frames where kakoune is rendering the status bar halfway up the screen.  It almost looks like your terminal is being resized - but it clearly isn't :)

**Comment by RemiIia** [comment]
Link to my entire config - http://www.filedropper.com/kakoune-config

**Comment by RemiIia** [comment]
With key `-n` kakoune render works fine.

**Comment by RemiIia** [comment]
Problem with relative numbers highlighter.
```
add-highlighter global/ number-lines -relative
```

**Comment by austinjones** [comment]
Thanks so much!  I reproduced it.  Working on a fix.

**Comment by austinjones** [comment]
Thanks so much!  I reproduced it.

**Comment by austinjones** [comment]
Yeah, it looks like it's caused by `-relative`.  Should be able to fix it now.  Thanks so much! 👍🏻

**Comment by austinjones** [comment]
@RemiIia I just pushed a fix in [v0.5.3](https://github.com/austinjones/tab-rs/releases/tag/v0.5.3).
