### ISSUE TITLE
mouse clicking or scrolling will cause unexpected inputs

### ISSUE THREAD

**Issue by foisonocean** [austinjones/tab-rs#288]
Today I installed tab-rs, and everything worked properly at the beginning. But after tab-rs runs serveral minutes, mouse clicking or scrolling would cause unexpected inputs.

https://user-images.githubusercontent.com/15059605/103139821-414a2780-471b-11eb-816a-f7d3ce488e27.mp4

**Comment by foisonocean** [comment]
I found this issue is probably caused by running tab-rs and [bottom](https://github.com/ClementTsang/bottom) together.

Steps to reproduce:

1. open "foo" tab.
1. open "bar" tab.
1. run `btm`.
1. press `e` to expand a bottom window.
1. press Ctrl-T to switch back to "foo" tab.
1. now mouse clicking begin to cause unexpected inputs

https://user-images.githubusercontent.com/15059605/103140128-d8b07a00-471d-11eb-8728-08399d764d69.mp4

I'm not sure this is a issue of tab-rs or bottom, but when I use bottom alone, I never found this issue.

**Comment by austinjones** [comment]
Looks like some kind of cursor mode needs to be reset when switching tabs.  I'll take a look at this.

**Comment by austinjones** [comment]
I reproduced this, and I have a fix!  Thanks for writing the steps to reproduce :)

It was a mouse select mode enabled by `btm` that needed to be reset when switching away.

**Comment by austinjones** [comment]
@foisonocean I just release [v0.5.4](https://github.com/austinjones/tab-rs/releases/tag/v0.5.4) with a fix!
