### ISSUE TITLE
Tab corrupts terminal display

### ISSUE THREAD

**Issue by kbd** [austinjones/tab-rs#289]
Just started using tab. Pretty much everything I do with tab seems to corrupt my terminal.

Here's a quick asciinema of just going into a named tab and then hitting ctrl+d:
https://asciinema.org/a/bxEMrmMMmOaJB6m90sUWFWUB1

You can't see it in the screencast, but just bringing up the fuzzy-finder with `tab` and then escaping it messes up my terminal somehow.

Here's a before and after of *just* running tab and hiting escape (zsh & iterm2):

![Screen Shot 2020-12-27 at 11 13 28 AM](https://user-images.githubusercontent.com/728060/103177093-a7769d80-4834-11eb-8df8-e04d56aab627.png)

![Screen Shot 2020-12-27 at 11 13 37 AM](https://user-images.githubusercontent.com/728060/103177095-a9d8f780-4834-11eb-95dd-b67a6265eba1.png)

The ⚡ at the start of my prompt is a double-width Unicode character. It's been really handy at helping find prompt escape bugs :)

**Comment by austinjones** [comment]
Hi @kbd,
Yeah, ctrl-d is likely to really mess with the terminal state.  The way tab works is when you connect to a session, it fully restores the terminal state for that session.  And when you disconnect/switch, it resets the terminal state.  Ctrl-d would put the tab client process in the background, and prevent it from printing the reset sequences.  ctrl-T ESC should work correctly, though.

I'm taking a look at the second issue you described though (tab, then esc).

**Comment by austinjones** [comment]
Hey @kbd,
Thanks for the bug report!  I was able to reproduce both issues.  I'm looking for a fix.

**Comment by austinjones** [comment]
I just released [v0.5.4](https://github.com/austinjones/tab-rs/releases/tag/v0.5.4) with a fix!  There were a few terminal state issues here - tab is supposed to reset the terminal state when you switch between sessions, but there were some edge cases that weren't handled properly.

**Comment by kbd** [comment]
Wow, looks like it works flawlessly now! Even with bugs I was still using it sometimes (but I'd have to close the terminal window after I was done with the thing). Now I can use it without fear. This is great, thanks so much for this tool.
