### ISSUE TITLE
use Command key instead Control

### ISSUE THREAD

**Issue by Stanislav-Lapata** [austinjones/tab-rs#297]
Thanks for your wonderful project.

Could you change Control key to Command by default for Mac OS?

**Comment by austinjones** [comment]
Hi @Stanislav-Lapata,
I'm glad you are finding it useful!

I don't think I can implement this in tab - as terminal apps don't receive any input when cmd-chars are pressed.  You might be able to configure this in your terminal emulator though by binding cmd-T to send the ctrl-T character (hex is 0x14, name is DC4).

I just tried it in iTerm and it worked.  Here is a screenshot:

<img width="443" alt="Screen Shot 2021-01-01 at 11 13 24 PM" src="https://user-images.githubusercontent.com/2111479/103450625-2467a400-4c87-11eb-9d07-2de5a7d16afd.png">
