### ISSUE TITLE
Inline version of fuzzy-finder?

### ISSUE THREAD

**Issue by kbd** [austinjones/tab-rs#302]
With `fzf` I use the `--height` option to make it not go "fullscreen". With tab, if I type `tab` or ctrl-t, then decide not to go into one of the sessions and hit escape, it annoyingly still `clear`s my current session.

----

Also, fwiw, I tried to see what would happen if I piped the name of a tab into `tab` so I could actually use it with `fzf` easily:

```
$ echo one | tab
thread 'tokio-runtime-worker' panicked at 'failed to enable raw mode: IoError(Os { code: 25, kind: Other, message: "Inappropriate ioctl for device" })', /Users/kbd/.cargo/registry/src/github.com-1ecc6299db9ec823/tab-command-0.5.4/src/service/terminal.rs:32:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by austinjones** [comment]
I think there a few things I could do here:
- I think I could make `tab; ESC` preserve your command history.  It wouldn't work if you had disconnected from a session though - as tab resets the terminal state when disconnecting (removing the stdout from your root shell from the buffer). 
- It definitely makes sense to have `echo foo | tab` do something.  Maybe open the fuzzy finder with the input as a query.

**Comment by kbd** [comment]
Just so I'm clear, here's a quick screencast of what I'm talking about with the first point. This is just opening tab up and hitting escape:

![t-rec](https://user-images.githubusercontent.com/728060/103499825-afbb7380-4e06-11eb-9d37-33062426ad57.gif)

**Comment by austinjones** [comment]
Yeah, that's expected behavior at the moment.  I think I can make it better w/ the alternate buffer though.

**Comment by austinjones** [comment]
Ah, the `inappropriate ioctl` error is an upstream issue in crossterm: https://github.com/crossterm-rs/crossterm/issues/396

I was able to fix the 'clearing' issue though.  It'll be going out with v0.6.0.
