### ISSUE TITLE
-w not closing tabs

### ISSUE THREAD

**Issue by kbd** [austinjones/tab-rs#303]
See screenshot:

![Screen Shot 2021-01-03 at 8 26 40 PM](https://user-images.githubusercontent.com/728060/103498461-1a1de500-4e02-11eb-91b4-ec65f13530b2.png)

**Comment by austinjones** [comment]
Hi @kbd,
I think I have a fix for this.  I'll try to push a release soon.

**Comment by austinjones** [comment]
This is fixed in [v0.5.5](https://github.com/austinjones/tab-rs/releases/tag/v0.5.5).  The client was asking the daemon to disconnect the session, instead of close it (doh!).
