### ISSUE TITLE
Suggestion: "tab -" to switch to prior session

### ISSUE THREAD

**Issue by kbd** [austinjones/tab-rs#304]
Just like `cd -` switches to your prior directory and `git switch -` switches to your prior branch, I think it'd make sense if tab let you `tab -` to go to your prior session.

```
$ tab -
error: Invalid value for '<TAB>': tab name may not begin with a dash
```

Dash isn't used currently ^

**Comment by austinjones** [comment]
Really cool idea!  I like it.

**Comment by austinjones** [comment]
I've implemented this on a PR - great suggestion!  It's smooth.

When outside a session, it switches to the most recently selected tab:
```
$ tab foo
foo/ $ <disconnect>
$ tab -
foo/ $
```

When within a session, it switches to the previously selected tab
```
$ tab foo
foo/ $ tab bar
bar/ $ tab -
foo/ $
```
