### ISSUE TITLE
install completion error

### ISSUE THREAD

**Issue by FuGangqiang** [austinjones/tab-rs#310]
```
$ tab --install zsh
Error: tab could not find a suitable completion directory.  supported directories are: '~/.oh-my-zsh/completions' and '/usr/local/share/zsh/site-functions'
```
I do not use oh-my-zsh, so this command report error

the install command should be like `rustup`:

```
rustup completions zsh > ~/.zsh/completion/_rustup

tab --install zsh > ~/.zsh/completion/_tab
```

**Comment by austinjones** [comment]
Hi @FuGangqiang,
You can install it that way with `tab --completion zsh > ~/.zsh/completion/_tab`.  The install command is meant to be a helper to quickly get tab working with all your installed shells.  

There are some issues with the zsh installer though - it's quite hard to find a way to install completions in a cross-platform way.  I'll take a look at this though and see if I can make it work for your environment.

**Comment by FuGangqiang** [comment]
thanks for you advice command `tab --completion zsh`, this is what I want that do not be found in the readme file
