### ISSUE TITLE
`Esc` after `Ctrl+T` exits tabs completely

### ISSUE THREAD

**Issue by shytikov** [austinjones/tab-rs#314]
I see kind of none-intuitive (for me) behaviour: when I press `Ctrl+T` and then press `Esc` I'm ending up outside tabs. While I expect to stay in the tab from which I have initially pressed `Ctrl+T`.

Option to exit from `tab` context is very cool, as I would love to have an option more seamlessly detach from tab, but the way it is done via escape for me looks kind of too sleek. For `vim` person who used to press `Esc` all over the place and often even twice (to be sure :) that behaviour is quite irritating – all over sudden you end up outside the `tab` with no warning and `Ctrl+T` not working anymore.

I'm using `tabs` on Mac, `zsh` / `alacritty` / `starship`.

**Comment by austinjones** [comment]
Yeah, I've run into this as well.  I think it'd be a good change, but I'd need to figure out another sequence to replace `ctrl-T ESC` when you need to kill the command-line client.  Any ideas?

**Comment by shytikov** [comment]
I believe fuzzy finder is the good place to have that command. But maybe it could be separate bullet along with other tabs. Last line, for example. I don't think adding another shortcut like `ctrl-T ctrl-Q` will be inline with the main idea of single powerful shortcut. But maybe some special symbol could indicate "virtual" tab, which actually means "exit". I assume `//` could be invalid tab name which could be used in this case. 

But it should be something sleek, obvious and usable, so main idea of the app won't be compromised.

**Comment by austinjones** [comment]
Ah I think ctrl-C would work for exit.  Then ESC could quit if you haven't selected any tabs, and reconnect if you just came from a session.

**Comment by shytikov** [comment]
You mean `ESC` will bring you back to your previous tab, if you haven't selected anything?

**Comment by jcvar** [comment]
I agree that using `ctrl-t <Esc>` to exit to the root shell can be a bit counter intuitive but it is a necessary option regardless.

I had suggested adding a default option (`ctrl-t <Enter>`) in #224, which can be used to return to the previous tab.

**Comment by austinjones** [comment]
I have this implemented - and I immediately love it :D

`ctrl-T ctrl-C` can now be used to quit the fuzzy finder.  And if you just launched tab (no previously selected tab for that client), ESC quits.
