### ISSUE TITLE
crashes with Cyrillic characters

### ISSUE THREAD

**Issue by Stanislav-Lapata** [austinjones/tab-rs#335]
if I accidentally enter Cyrillic characters, the tab crashes

OS: macOS
tab version: 0.5.3

https://user-images.githubusercontent.com/12072329/106284495-5ce1aa00-6254-11eb-9a0c-4db645d0f1ff.mov

**Comment by austinjones** [comment]
I'll take a look at this!

**Comment by austinjones** [comment]
I just pushed a fix in [v0.5.7](https://github.com/austinjones/tab-rs/releases/tag/v0.5.7).  It should work correctly now (and Cyrillic tab names should work too!).
