### ISSUE TITLE
Dialoguer 0.7.0 does not compile anymore

### ISSUE THREAD

**Issue by dtomvan** [austinjones/tab-rs#361]
For some reason while trying to compile tab-rs, its dependency-check errors:
```
❯ cargo install tab                                                                                                                                                                   15:17:53
    Updating crates.io index
  Installing tab v0.5.7
error: failed to compile `tab v0.5.7`, intermediate artifacts can be found at `/tmp/cargo-install0nuK0R`

Caused by:
  failed to select a version for the requirement `zeroize = "^0.9.3"`
  candidate versions found which didn't match: 1.3.0, 1.2.0, 1.1.1, ...
  location searched: crates.io index
  required by package `dialoguer v0.7.0`
      ... which is depended on by `tab v0.5.7`
```

**Comment by astrolemonade** [comment]
I managed to build tab on Linux on both debug and release modes. Could you try again?
I tried to build it on WSL earlier this day and I received the error you mentioned. Maybe it was fixed.

**Comment by gnur** [comment]
On Ubuntu 20.04 I can't get it to install as well:

```
erwin@sanny:~$ cargo version
cargo 1.52.0 (69767412a 2021-04-21)
erwin@sanny:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
erwin@sanny:~$ cargo install tab
    Updating crates.io index
  Installing tab v0.5.7
error: failed to compile `tab v0.5.7`, intermediate artifacts can be found at `/tmp/cargo-installUvAdpY`

Caused by:
  failed to select a version for the requirement `zeroize = "^0.9.3"`
  candidate versions found which didn't match: 1.3.0, 1.2.0, 1.1.1, ...
  location searched: crates.io index
  required by package `dialoguer v0.7.0`
      ... which is depended on by `tab v0.5.7`
```

**Comment by reflog** [comment]
Same here on Arch:
```
➜ cargo install tab
    Updating crates.io index
  Downloaded tab v0.5.7
  Downloaded 1 crate (30.0 KB) in 1.99s
  Installing tab v0.5.7
error: failed to compile `tab v0.5.7`, intermediate artifacts can be found at `/tmp/cargo-installl1Y2v3`

Caused by:
  failed to select a version for the requirement `zeroize = "^0.9.3"`
  candidate versions found which didn't match: 1.3.0, 1.2.0, 1.1.1, ...
  location searched: crates.io index
  required by package `dialoguer v0.7.0`
      ... which is depended on by `tab v0.5.7`
```

**Comment by dtomvan** [comment]
> I managed to build tab on Linux on both debug and release modes. Could you try again?
> I tried to build it on WSL earlier this day and I received the error you mentioned. Maybe it was fixed.

Nope, still doesn't work:
```
❯ cargo install tab
    Updating crates.io index
  Downloaded tab v0.5.7
  Downloaded 1 crate (30.0 KB) in 1.16s
  Installing tab v0.5.7
error: failed to compile `tab v0.5.7`, intermediate artifacts can be found at `/tmp/cargo-install5ucHke`

Caused by:
  failed to select a version for the requirement `zeroize = "^0.9.3"`
  candidate versions found which didn't match: 1.3.0, 1.2.0, 1.1.1, ...
  location searched: crates.io index
  required by package `dialoguer v0.7.0`
      ... which is depended on by `tab v0.5.7`
```

**Comment by dtomvan** [comment]
Oh, I just realized that I posted the same as the guy above me

**Comment by dtomvan** [comment]
Maybe related to #351?

**Comment by xaocon** [comment]
> Maybe related to #351?

Yeah, looks like it to me. Updating `dialoguer` to 0.8 worked for me. Haven't seen any issues.

**Comment by dmgolembiowski** [comment]
> *Disclaimer:* 
> The maintainers are entitled to mark this as off-topic if they wish, but I believe this is what many others are coming to this issue thread to see.

`cargo install tab` does not work. I dug into the github workflows and saw how other people could be installing tab, but potentially neglecting to share how they're doing it. The procedure I've used to get an installation of tab on my system is:

```sh
# Gather the source repo
git clone https://github.com/austinjones/tab-rs tab && cd tab
```
```sh
# Replace `v0.5.7` with your desired version.
# You can run `git branch -d <TAB>` to see the available versions
git checkout v0.5.7
```
```sh
cargo build --release --bin tab
```
```sh
# Preserve the installation until it can be installed from crates.io
_entry="export PATH=$PWD/target/release:\$PATH"
echo $_entry >> ~/.bashrc && exec bash
```
```sh
# Installing completions for your shell.
tab --install bash
```

Please consider keeping this comment available. It's meaningful to newcomers who want to engage with this software.

**Comment by guy-who-googles** [comment]
It's been a while, but in case it's of use, I believe I'm using the [pre-compiled binaries](https://github.com/austinjones/tab-rs/releases).

**Comment by joshbainbridge** [comment]
I know this is an old thread, but just wanting to give an update for anyone else who comes across this issue. The current `main` branch now has an updated version of `dialoguer`, so you can build and install `tab` by just running:

```bash
cargo install --path tab
```

or as @guy-who-googles says, use a pre-compiled binary.

That said, as of writing, the current released version (v0.5.7), and therefor the version available via crates.io, does not include this update. So running:

```bash
brew install austinjones/taps/tab
```

or:

```bash
cargo install tab
```

appears to still be broken. I'd suggest that a minor version release might help new users, just so that the installation instructions on the README page work. But appreciate this is a side project and the maintainer might be busy.

Also wanted to add (as a first time writer on this project), a massive thank you to the maintainer. I understand this might not be their main focus, but it's great to see a fresh take on multiplexers and I've enjoyed using `tab` after recently discovering it. It's a great tool!

**Comment by dtomvan** [comment]
> The current `main` branch now has an updated version of `dialoguer`, so you can build and install `tab` by just running:

Great! I think this issue is alright to "finally" be closed, then?

> a massive thank you to the maintainer. I understand this might not be their main focus, but it's great to see a fresh take on multiplexers and I've enjoyed using tab after recently discovering it. It's a great tool!

100%. I very much like the way it's organized. When I was using it in 2021 it was very nice, but maybe a bit slow when using heavy interactive programs such as TUI editors (neovim, emacs, nano, kakoune etc.). Still very much a +1 on that!

**Comment by joshbainbridge** [comment]
> Great! I think this issue is alright to "finally" be closed, then?

I would agree, appears to be resolved.
