### ISSUE TITLE
Explain which workspace tabs are active when `tab -l` is called.

### ISSUE THREAD

**Issue by austinjones** [austinjones/tab-rs#51]
In `tab -l` output, explain which workspace tabs are currently 'active' via the user's working directory.  Here is an example where the user is in `~/workspace/tab-rs`.
```
Available tabs:
    any/              (random tasks)
  > home/             (my home directory)
    lifeline/         (lifeline-rs, a dependency injection library for async channels)
  > workpace/         (my repositories)
  > tab/              (the tab-rs terminal multiplexer)
```

**Comment by austinjones** [comment]
@casonadams if you are interested in contributing a PR I think this one would be fun.  The idea here is to explain a bit better which workspace tabs are 'active' - by testing if the workspace tab is equal (or a parent) to the current directory.

WorkspaceTab has a `directory` property that can be used.  It might come from a workspace/repo config, or the directory an anonymous tab was spawned from (e.g. I ran `tab foo`).

The code is here: https://github.com/austinjones/tab-rs/blob/main/tab-command/src/service/main/list_tabs.rs#L44

Also, a few things on developing locally:
- Any crates you modify (in this case tab-command) need to have a patch entry uncommented: https://github.com/austinjones/tab-rs/blob/main/Cargo.toml#L17. Otherwise the `tab` binary will be built against a published crates.io version.
- You can run tab in debug mode using this script: https://github.com/austinjones/tab-rs/blob/main/scripts/run.sh.  If you run `tab --shutdown` before `run.sh`, it'll relaunch the daemon and PTY processes in debug mode too!

**Comment by casonadams** [comment]
So what does `active` mean here.

I am assuming that `active` means there is a tab running, rather than just a workspace defined?

**Comment by austinjones** [comment]
Just that the user's working directory is within the tab's directory.  The idea is that it'll make it more clear when you are within a workspace or a repo.

Your PR screenshot looks awesome.  I'll review it in a sec.

**Comment by austinjones** [comment]
Merged!  It's working great :)
